DROP TABLE IF EXISTS `pb1`;
CREATE TABLE `pb1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  `email` TEXT NULL,
  `website` TEXT NULL,
  `about` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
